### ISSUE TITLE
was one-gpu training supported ?

### ISSUE THREAD

**Issue by ThomaswellY** [Flame-Chasers/RaSa#12]
Hi , Thanks for your owesome work !
i was doing experiment on your code, and found the standard way to start training is limited to torch.distributde.run.
And if i wanna debug your code line by line, there would be lots modification involved in (because concat_all_gather is unavoidable in _dequeue_and_enqueue, which just based on torch.distributed.get_world_size())
 So i wonder, if you have any plan to expose your early version of code(if only it is not special for torch.distributed.run)                                  
Sincerely looking for your reply~

**Comment by byougert** [comment]
Hi @ThomaswellY , thanks for your interest in our work.
Of course you can debug the code on a single gpu, just by modifying the [nproc_per_node](https://github.com/Flame-Chasers/RaSa/blob/bd16aa1a15f149548a90d196fcf10a27d7ab7c66/shell/cuhk-train.sh#L4) to 1.
