### ISSUE TITLE
where is the code of cross-modal encoder?

### ISSUE THREAD

**Issue by colinzhaoxp** [Flame-Chasers/RaSa#4]
Thank you for opening the code! it's wonderful work.
But I'm confused that **where is the implementation code for the cross-modal encoder.** 
I didn't find the code in the **model_person_search.py** file. 
looking forward to your reply, very much!

**Comment by byougert** [comment]
Hi,
thanks for your interest.
In fact, we reimplement BERT in models/xbert.py, in which we add an argument “mode” in the forward function to indicate whether to perform text encoding (when mode == "text") or cross-modal encoding (when mode == "fusion"), as shown in [BertModel](https://github.com/Flame-Chasers/RaSa/blob/bd16aa1a15f149548a90d196fcf10a27d7ab7c66/models/xbert.py#L956) and [BertEncoder](https://github.com/Flame-Chasers/RaSa/blob/bd16aa1a15f149548a90d196fcf10a27d7ab7c66/models/xbert.py#L548C1-L558C59).

**Comment by colinzhaoxp** [comment]
thanks for your answer!
