### ISSUE TITLE
强弱正样本对的标签何来？

### ISSUE THREAD

**Issue by Mudwall** [Flame-Chasers/RaSa#5]
作者你好，非常欣赏你们的这篇工作，也感谢能开源代码。我这边看了论文，对3.2节的 “We propose a Positive Relation Detection (PRD)pretext task to detect the type of the positive pair (i.e., strong or weak), which is formulated as:.....where (I, Tp) denotes a positive pair, y^prd is the ground truth label (i.e., [1, 0]⊤ for the strong positive pair and [0, 1]⊤ for the weak pair)"，这里提到的强弱正样本对的标签y^prd 是哪里来的？公开的数据集里没有这个标签，是你们标定的吗？

**Comment by byougert** [comment]
你好， @Mudwall 
非常感谢你对RaSa的关注。

强弱正样本的标签是可以根据现有数据集的标注获得的，无需额外的人工标注。

在现有数据集中，我们是可以知道图像和文本的对应关系和行人id标签，
我们定义：
强正样本对：图像和文本的行人id相同，且图像和文本具有对应关系
弱正样本对：图像和文本的行人id相同，但图像和文本不具有对应关系

例如对于数据集S={<x1, t1, y1>, <x1,t2, y1>, <x2, t3, y1>, <x2, t4, y1>, ...}，其中x为图像，t为文本，y为行人id标签，t1和t2是根据图x1标注来的，t3和t4是根据图x2标注来的。
由于图像和文本都是描述行人y1，他们每一个图像文本对都构成正样本对。
但是，<x1, t1>, <x1, t2> <x2, t3>, <x2, t4>为强正样本对；而<x1, t3>, <x1, t4> <x2, t1>, <x2, t2>为弱正样本对。

希望我的回答能够帮助到你，如果还有任何疑问，请随时与我联系，谢谢。

**Comment by shams2023** [comment]
作者你好，那么是不是可以这样理解：

p-ITM里面所说的概率p，是不是在前期准备的时候用到的（即 在使用ITM之前按照概率p准备好强正对和弱正对，然后在进行ITM区分正负样本）

P-ITM的作用就是为了区分正负样本对的（即 和通用的ITM的作用相同），就是为了找出来哪些是正样本，为后续的PRD工作打基础的？
而PRD的作用是为了将p-ITM区分出来的正样本对再次进行划分，即找到哪些是强正对，哪些是弱正对，从而给予弱正对一个小的权重，即达到利用它的有效信息，又可以有效的避免弱正对所带来的噪声干扰问题
谢谢！

**Comment by byougert** [comment]
你好， @shams2023 

强弱正样本在标签层面就可以区分的，并非是“PRD的作用是为了**将p-ITM区分出来的正样本**对再次进行划分”。

对于一系列数据对<I, T>，我们在标签层面是可以得到他们的ground truth label（包括正负关系label和强弱正关系label，至于如何得到强弱正关系label，请参考[这里](https://github.com/Flame-Chasers/RaSa/issues/5#issuecomment-1663409598)），p-ITM是区分正负关系，PRD是区分强弱正关系。所用的loss均为交叉熵loss，其目的是能够正确区分样本间的关系，所以我们才提出了relation-aware learning。

PRD的作用正如你理解的那样， 是为了“利用用它的有效信息，又可以有效的避免弱正对所带来的噪声干扰问题”。

感谢你的关注。

**Comment by shams2023** [comment]
谢谢作者的解惑，我一直以为p-ITM和PRD是前后关系，即先执行p-ITM来区分正负关系，得到正样本对（包括强弱正对），再对得到的正样本对进行PRD的操作，从而区分强弱正关系。
其实他们之间是相互独立的，并非具有硬性的前后关系

**Comment by byougert** [comment]
感谢你的关注
