### ISSUE TITLE
Error of running code

### ISSUE THREAD

**Issue by clarkhedi** [Flame-Chasers/RaSa#6]
![image](https://github.com/Flame-Chasers/RaSa/assets/47168403/687850db-1cba-4ba1-80ca-68bc42cda7c3)

Thank you so much for your open-source work!

As shown in the above figure, I meet the question. What is the reason for this? Thank you very much for your help.

**Comment by clarkhedi** [comment]
I have solve the question.

**Comment by shams2023** [comment]
> I have solve the question.

I have also encountered this problem now. How can I solve it?
thanks!

**Comment by byougert** [comment]
Hi @clarkhedi @shams2023 ,

This error typically occurs when attempting to load BERT and Tokenizer online, which downloads the model's weights from the default url. However, there might be **accessibility** issues with this URL. 

Instead, you can proactively download the weights file beforehand and save it in your local cache directory (e.g., /data/cache). During the initialization of BERT, you can then specify the exact path to the saved weights file (e.g., BertForMaskedLM.from_pretrained('/data/cache')). By doing so, you ensure that the weights are readily available and avoid relying on the online download.

**Comment by shams2023** [comment]
> 嗨，
> 
> 当尝试在线加载 BERT 和 Tokenizer 时，通常会发生此错误，这会从默认 url 下载模型的权重。但是，此 URL 可能存在**辅助功能**问题。
> 
> 相反，您可以事先主动下载权重文件并将其保存在本地缓存目录（例如 /data/cache）中。在 BERT 初始化期间，您可以指定保存权重文件的确切路径（例如，BertForMaskedLM.from_pretrained（'/data/cache'））。通过这样做，您可以确保权重随时可用，并避免依赖在线下载。

非常感谢（thanks)
