### ISSUE TITLE
Why does the dataloader in RaSa return the value like this?

### ISSUE THREAD

**Issue by shams2023** [Flame-Chasers/RaSa#7]
![image](https://github.com/Flame-Chasers/RaSa/assets/141383792/ed0fa1a5-77d2-4ec6-8644-f8fa7e6d8716)
This is a great job!
Thank you for your open source!
Why train_ In the loader, there will be phenomena in the image, and the text can still be understood. One is the original text, and the other is the enhanced text. But the images are all transformed through the same transformer, and they are the same. Why is this design necessary?

**Comment by byougert** [comment]
Hi @shams2023 ,

Thank you for your interest in our work. We apply data augmentation to images to enhance the generalization capability of our model. Inspired by the contrastive learning approaches like MoCo and SimCLR, we further align the two augmentated views of the images to learn transformation-invariant visual representations.

Please let me know if you have any further questions.

**Comment by shams2023** [comment]
> 嗨，
> 
> 感谢您对我们工作的关注。我们将数据增强应用于图像以增强模型的泛化能力。受MoCo和SimCLR等对比学习方法的启发，我们进一步对齐图像的两个增强视图，以学习转换不变的视觉表示。
> 
> 如果您有任何其他问题，请告诉我。

thanks,sogood!
