### ISSUE TITLE
CUHK-PEDES数据集

### ISSUE THREAD

**Issue by LYY123444** [Flame-Chasers/RaSa#8]
请问CUHK-PEDES数据集怎么下载的，发邮件吗？

**Comment by byougert** [comment]
@LYY123444 ，
你好，CUHK-PEDES数据集目前最佳的获取方式还是给作者发邮件获取下载链接。
作者一般回复得还是挺快的。

**Comment by womeizhaol** [comment]
> [@LYY123444](https://github.com/LYY123444) ， 你好，CUHK-PEDES数据集目前最佳的获取方式还是给作者发邮件获取下载链接。 作者一般回复得还是挺快的。

您好，我发了邮件没有回，请问可以分享一下CUHK-PEDES数据集吗
