### ISSUE TITLE
关于模型的参数量

### ISSUE THREAD

**Issue by stxg13056** [Flame-Chasers/RaSa#9]
你好，我想知道你们这项工作的模型参数量具体是多少，可以方便告知吗？

**Comment by kangbin98** [comment]
出现该报错RuntimeError: invalid multinomial distribution (sum of probabilities <= 0) 请问如何处理

**Comment by byougert** [comment]
Hi, @stxg13056 ，
The number of trainable parameters in RaSa is 210M, which can be easily calculated as follows:
`print('Total params: %2.fM' % (sum(p.numel() for p in model.parameters() if p.requires_grad) / 1000000.0))`

Thx for your interests in our work.😋

**Comment by byougert** [comment]
Hi, @kangbin98 ,
This error may occur when calling `torch.multinomial(input, ...)` which is aimed at sampling tensors according to the multinomial probability distribution in `input` .

As mentioned in pytorch official [documents](https://pytorch.org/docs/1.9.1/generated/torch.multinomial.html?highlight=multinomial), the rows of input do not need to sum to one (in which case we use the values as weights), but must be **non-negative, finite** and have a **non-zero** sum.

You could recheck the code and ensure the validity of `input`.
